server:
    port: 9001
spring:
  application:
    name: spring-boot-admin
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      discovery:
        ignored-services: spring-boot-admin
